"""Build the synchronous browser catalog; --check detects stale shipped assets."""

import argparse
import json
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "dashboard" / "static"


def build():
    catalogs = {
        language: json.loads((ROOT / "locales" / f"{language}.json").read_text(encoding="utf-8"))
        for language in ("en", "ru")
    }
    if catalogs["en"].keys() != catalogs["ru"].keys():
        raise ValueError("EN/RU catalog keys differ")
    # Russian source messages double as stable gettext-style keys. Include only
    # non-identity Russian entries (e.g. plural forms) in the browser bundle.
    catalogs["ru"] = {k: v for k, v in catalogs["ru"].items() if k != v}
    return (
        '/* Generated by scripts/build_i18n.py. Edit locales/*.json. */\n"use strict";\n'
        + "window.PZ_TRANSLATIONS = "
        + json.dumps(catalogs, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ROOT / "catalogs.js"
    expected = build()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("Browser catalog is stale; run python scripts/build_i18n.py")
    else:
        # A running server must see either the old complete catalog or the new
        # complete catalog, never an empty/partially written script.
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=ROOT, prefix=".catalogs-", suffix=".tmp", delete=False
        ) as temporary:
            temporary.write(expected)
            temporary_path = Path(temporary.name)
        try:
            temporary_path.replace(output)
        finally:
            temporary_path.unlink(missing_ok=True)
